theme: jekyll-theme-hacker

title: "Nitheesh"
description: "Forbidden Island - Java Board Game Recreation"
url: "https://nitheesh-cpu.github.io/"
baseurl: "/Forbidden-Island/"

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed

# Navigation - Links back to main portfolio site
navigation:
  - name: "Home"
    link: "https://nitheesh-cpu.github.io/"
  - name: "Projects"
    link: "https://nitheesh-cpu.github.io/projects.html"
  - name: "Resume"
    link: "https://nitheesh-cpu.github.io/resume.html"
  - name: "Contact"
    link: "https://nitheesh-cpu.github.io/contact.html"

# Social links
social:
  github: "https://github.com/nitheesh-cpu"
  linkedin: "https://www.linkedin.com/in/nitheesh-kodarapu-7529b1272"
  instagram: "https://www.instagram.com/nitheeesh_/"

# Exclude from processing
exclude:
  - "*.java"
  - "*.class"
  - "target/"
  - "out/"
  - ".idea/"
  - "lib/"
  - "*.jar"
  - "pom.xml"
  - ".git/"
  - ".gitignore"
  - "forbiddenisland.gif"
